<?php
/**
 * @author Tomohito Inoue <hypernumbernet@users.noreply.github.com>
 */
?>
<!DOCTYPE html>
<meta charset="utf-8">
<title>Conecmo</title>
<?= \Ae\Utl\Html::loadCss('js/jquery-ui-1.11.4/jquery-ui.css') ?>
<?= \Ae\Utl\Html::loadCss('all.css') ?>
<?= \Ae\Utl\Html::loadCss('font-awesome-4.6.3/css/font-awesome.css') ?>
<script src="js/lib/jquery-2.2.4.js"></script>
<script src="js/jquery-ui-1.11.4/jquery-ui.js"></script>
<script src="js/lib/jquery.mousewheel3.1.13.js"></script>
<?= $js ?>
<?= $main ?>
